<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BatchPlotPlus.AutoCAD\BatchPlotPlus.AutoCAD.csproj" />
    <PackageReference Include="AutoCAD.NET" Version="24.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
